### ISSUE TITLE
changelog: v0.4.0 link and release date missing

### ISSUE THREAD

**Issue by tmplt** [atsams-rs/atsamx7x-rust#44]
See `CHANGELOG.md`, c.f. v0.3.0 entry.

**Comment by michalfita** [comment]
I think I've made mistake committing last changes coming into the release. On the machine I'm using for open-source work I don't have disk big enough to keep second copy just to release, so when I jump between branches sometimes it causes issues. I'll fix this soon, before we go for 0.4.1.
