### ISSUE TITLE
rustc 1.72.0: flooded with `warning: lint `const_err` has been removed: converted into hard error`

### ISSUE THREAD

**Issue by michalfita** [atsams-rs/atsamx7x-rust#63]
```
   Compiling atsamv71q19b v0.25.0 (/home/manveru/Projects/atsamx7x-rust/pac/atsamv71q19b)
warning: lint `const_err` has been removed: converted into hard error, see issue #71800 <https://github.com/rust-lang/rust/issues/71800> for more information
 --> pac/atsams70n19b/src/lib.rs:3:9
  |
3 | #![deny(const_err)]
  |         ^^^^^^^^^
  |
  = note: `#[warn(renamed_and_removed_lints)]` on by default
```
So, it's materialization of https://github.com/rust-lang/rust/issues/71800.

We need CI to actually test with MRV and latest.

**Comment by tmplt** [comment]
> We need CI to actually test with MRV and latest.

This is a good idea. Minimum would be a required to pass, but any errors from latest could be emitted as warnings for review in PRs.

**Comment by michalfita** [comment]
> any errors from latest could be emitted as warnings for review

Except GitHub contrary to GitLab cannot emit warning statues from builds. In general I find GitLab superior to GitHub, it's just much less popular choice for Rust's crates.

**Comment by tmplt** [comment]
I must have conflated the two.

**Comment by martinmortsell** [comment]
With the merge of #64 this issue is resolved, right?

**Comment by michalfita** [comment]
Yes, it is. We now need to move to PACs generated with newer `svd2rust` what I already exercised.
